task:
  name: "Silent ARP"
  description: >
    Establish connectivity, handle all ARP REQESTS in the controller. No broadcasts. Note, flooding could cause ping pong.
    A host has to sent something/an arp request before it is reachable. This way the controller learns about the host.
    Hosts on S1: "10.0.0.0/24", hosts on S2: "10.0.1.0/24". Good luck.
  scenario: "learning2"
  graph: |
    [ S1 ] -- { start: north } [ H1 ] { origin: S1; offset:  0,-2; }
    [ S1 ] -- { start: west } [ H2 ] { origin: S1; offset: -2, -1; }
    [ S1 ] -- { start: west } [ H3 ] { origin: S1; offset: -2, 1; }
    [ S1 ] -- { start: south } [ H4 ] { origin: S1; offset:  0, 2; }
    [ S1 ] -- { start: east } [ S2 ] { origin: S1; offset:  2, 0; }
    [ S2 ] -- { start: east } [ H6 ] { origin: S2; offset:  2, 1; }
    [ S2 ] -- { start: east } [ H7 ] { origin: S2; offset:  2, -1; }
    [ S2 ] -- { start: north } [ H8 ] { origin: S2; offset:  0,-2; }
    [ S2 ] -- { start: south } [ H5 ] { origin: S2; offset:  0, 2; }
  examination: 0
