task:
  name: "Load-balancer 1"
  description: >
    Distribute the traffic from host H1
    evenly among host H2 and H3. All
    traffic is directed to randomly chosen
    IP destination addresses in
    the subnet 22.0.0.0/8. All hosts
    are connected to each other by
    switch S1.
  scenario: "loadbalancer1"
  graph: |
    [ S1 ] -- { start: north; label: 1 } [ H1 ] { origin: S1; offset: 0,-2; }
    [ S1 ] -- { start: east; label: 2 }  [ H2 ] { origin: S1; offset: 2,0; }
    [ S1 ] -- { start: west; label: 3 }  [ H3 ] { origin: S1; offset: -2,0; }
  examination: 1
